services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py
      - MONGO_URI=mongodb://db:27017/rps_db

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: